default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default