default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: shortlink
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: shortlink_test

production:
  <<: *default